### ISSUE TITLE
Json Mapping

### ISSUE THREAD

**Issue by SaidaniMohamed** [Hamza5/DZ_COVID19_data_retrieval#1]
salam 3alaykom @Hamza5 , thanks for your help

if I understand well, you get the data from two def resources, and they don't have the same mapping, which made a problem for my case!

waiting for your feedback^^

**Comment by Hamza5** [comment]
@SaidaniMohamed: of course they don't have the exact mapping since the services don't offer the same data. However, if you are asking about the common data, no, the mapping is the same. For example, for all the services, the province is always the main key, and the code of the province is always used as a key. Another example is the number of the confirmed cases, they are always referenced as `cases` no mater the source.

**Comment by Hamza5** [comment]
The mapping has been changed slightly now. `cases` is now `confirmed`.
